[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "14.15.3", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "14.15.3", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' cloudinary.com res.cloudinary.com netlify.com app.netlify.com www.netlifystatus.com player.vimeo.com plausible.io; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://netlify-cdp-loader.netlify.app/netlify.js https://identity.netlify.com/v1/netlify-identity-widget.js https://cdn.jsdelivr.net https://media-library.cloudinary.com https://plausible.io/js/plausible.js plausible.io; worker-src 'self' blob:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
